name: auto-commit

on:
  push:
  pull_request:

jobs:
  formatted:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls
          touch test
          echo "this is test" >> test
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: Generate OpanApi YAML

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: git log --oneline
