name: auto-commit-trigger

on:
  push:
  pull_request:

jobs:
  formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
          echo ${{ secrets.PAT }}
          touch test
          echo "this is test" >> test
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: auto-commit

  build:
    runs-on: ubuntu-18.04
    needs: formatted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git log --oneline

