name: auto-commit

on:
  push:
  pull_request:

jobs:
  formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: |
          touch test
          echo "this is test" >> test
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: Generate OpanApi YAML

  build:
    runs-on: ubuntu-18.04
    needs: formatted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - run: |
          git log --oneline

